# Generated by Django 5.2.11 on 2026-04-03 16:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_language', models.CharField(default='en', max_length=2)),
                ('address_line_1', models.CharField(max_length=160)),
                ('address_line_2', models.CharField(blank=True, max_length=160)),
                ('district', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=12)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('12.915300'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('76.643800'), max_digits=9)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('color', models.CharField(default='#F1E0B8', max_length=20)),
                ('tag', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('electric', 'Electric'), ('petrol', 'Petrol')], max_length=12)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('is_available', models.BooleanField(default=False)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('max_service_radius_km', models.PositiveIntegerField(default=17)),
                ('photo_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('12.915300'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('76.643800'), max_digits=9)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('shop_type', models.CharField(choices=[('kirana', 'Kirana'), ('medical', 'Medical'), ('bakery', 'Bakery')], max_length=12)),
                ('area', models.CharField(max_length=120)),
                ('address_line_1', models.CharField(max_length=160)),
                ('address_line_2', models.CharField(blank=True, max_length=160)),
                ('district', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=12)),
                ('description', models.TextField(default='Local quick-commerce partner')),
                ('offer', models.CharField(default='Fresh local delivery', max_length=160)),
                ('image_url', models.URLField(blank=True)),
                ('is_open', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('12.915300'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('76.643800'), max_digits=9)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
                ('delivery_address', models.CharField(max_length=240)),
                ('customer_otp', models.CharField(default='123456', max_length=6)),
                ('customer_notes', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customerprofile')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.riderprofile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='core.shopownerprofile'),
        ),
    ]
