# Generated by Django 5.2.11 on 2026-04-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authotptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('shop', 'Store Owner'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=12),
        ),
    ]
