# Generated by Django 5.2.11 on 2026-04-04 05:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('customer_notes', models.CharField(blank=True, max_length=200)),
                ('delivery_address', models.CharField(max_length=240)),
                ('cart_snapshot', models.JSONField(blank=True, default=dict)),
                ('cart_signature', models.CharField(max_length=64)),
                ('receipt', models.CharField(blank=True, db_index=True, max_length=40)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, max_length=160)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='core.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.checkoutsession'),
        ),
    ]
