# Generated by Django 5.2.11 on 2026-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_checkoutsession_order_checkout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_collection_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online COD Payment'), ('cash', 'Cash Collected')], max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_payment_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_payment_link_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_payment_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_payment_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_qr_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_qr_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('qr_ready', 'QR Ready'), ('paid', 'Settled'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
    ]
