# Generated by Django 5.2.11 on 2026-04-04 22:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('khata', 'KhataBook Credit')], default='cod', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('khata', 'KhataBook Credit')], default='cod', max_length=12),
        ),
        migrations.CreateModel(
            name='KhataBookCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('collection_requested', 'Collection Requested'), ('paid', 'Paid')], default='open', max_length=24)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('settlement_method', models.CharField(blank=True, choices=[('cod_upi', 'COD / UPI Collection'), ('razorpay_upi', 'Razorpay UPI')], max_length=24)),
                ('collection_requested_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, max_length=160)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatabook_cycles', to='core.customerprofile')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='khata_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.khatabookcycle'),
        ),
        migrations.AddConstraint(
            model_name='khatabookcycle',
            constraint=models.UniqueConstraint(fields=('customer', 'week_start'), name='unique_khatabook_cycle_per_customer_week'),
        ),
    ]
