# Generated by Django 5.2.11 on 2026-04-04 23:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_credit_due_date_order_credit_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataBookCollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('12.915300'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('76.643800'), max_digits=9)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('collection_address', models.CharField(max_length=240)),
                ('collection_notes', models.CharField(blank=True, max_length=200)),
                ('collection_otp', models.CharField(blank=True, max_length=6)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatabook_collection_requests', to='core.customerprofile')),
                ('khata_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to='core.khatabookcycle')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khatabook_collection_requests', to='core.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
