# Generated by Django 5.2.11 on 2026-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_khatabookcollectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
