# Generated by Django 5.2.11 on 2026-04-05 09:38

from decimal import Decimal
from django.db import migrations, models


def seed_delivery_slot_settings(apps, schema_editor):
    DeliverySlotSetting = apps.get_model('core', 'DeliverySlotSetting')
    defaults = [
        {
            'code': 'PRIORITY',
            'name': 'Priority Delivery',
            'description': 'Fast delivery with highest priority.',
            'time_label': '30-40 minutes',
            'time_limit_minutes': 40,
            'delivery_fee': Decimal('20.00'),
            'color': 'red',
            'priority_level': 1,
            'tag': 'Fastest',
        },
        {
            'code': 'ECO',
            'name': 'Eco Delivery',
            'description': 'Optimized route delivery.',
            'time_label': '1-4 hours',
            'time_limit_minutes': 240,
            'delivery_fee': Decimal('10.00'),
            'color': 'green',
            'priority_level': 2,
            'tag': 'Recommended',
        },
        {
            'code': 'COST_SAVER',
            'name': 'Cost Saver',
            'description': 'Delivered during low traffic routes.',
            'time_label': '4-8 hours',
            'time_limit_minutes': 480,
            'delivery_fee': Decimal('5.00'),
            'color': 'blue',
            'priority_level': 3,
            'tag': 'Save Money',
        },
        {
            'code': 'BUDGET',
            'name': 'Budget Delivery',
            'description': 'Lowest cost delivery with flexible timing.',
            'time_label': '8-12 hours',
            'time_limit_minutes': 720,
            'delivery_fee': Decimal('0.00'),
            'color': 'gray',
            'priority_level': 4,
            'tag': 'Lowest Cost',
        },
    ]
    for slot in defaults:
        DeliverySlotSetting.objects.update_or_create(code=slot['code'], defaults=slot)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_delivery_deadline_order_delivery_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('PRIORITY', 'Priority Delivery'), ('ECO', 'Eco Delivery'), ('COST_SAVER', 'Cost Saver'), ('BUDGET', 'Budget Delivery')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_label', models.CharField(max_length=40)),
                ('time_limit_minutes', models.PositiveIntegerField(default=240)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('priority_level', models.PositiveSmallIntegerField(default=1)),
                ('tag', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Delivery slot setting',
                'verbose_name_plural': 'Delivery slot settings',
                'ordering': ['priority_level', 'code'],
            },
        ),
        migrations.RunPython(seed_delivery_slot_settings, noop_reverse),
    ]
