# Generated by Django 5.2.11 on 2026-04-05 13:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deliveryslotsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='khatabook_credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='khatabook_plan',
            field=models.CharField(choices=[('free', 'Free Rs. 1,000'), ('boost_3000', 'Boost Rs. 3,000'), ('boost_5000', 'Boost Rs. 5,000')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='khatabook_subscription_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KhataBookSubscriptionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('free', 'Free Rs. 1,000'), ('boost_3000', 'Boost Rs. 3,000'), ('boost_5000', 'Boost Rs. 5,000')], max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, max_length=160)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatabook_subscription_purchases', to='core.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
