from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/login/', views.login_view, name='login'),
    path('auth/google/', views.google_auth_view, name='google_auth'),
    path('auth/register/', views.register_view, name='register'),
    path('auth/email-otp/', views.email_otp_view, name='email_otp'),
    path('support/', views.support_view, name='support'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/mark-all-read/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('notifications/<int:notification_id>/mark-read/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/<int:notification_id>/delete/', views.notification_delete, name='notification_delete'),
    path('notifications/<int:notification_id>/open/', views.notification_open, name='notification_open'),
    path('orders/<int:order_id>/', views.order_detail_view, name='order_detail'),
    path('orders/<int:order_id>/tracking/', views.order_tracking_view, name='order_tracking'),
    path('logout/', views.logout_view, name='logout'),
    path('customer/start/', views.customer_start, name='customer_start'),
    path('customer/dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('customer/location/update/', views.customer_update_location, name='customer_update_location'),
    path('customer/stores/<slug:shop_slug>/', views.customer_store_detail_view, name='customer_store_detail'),
    path('customer/cart/', views.customer_cart_view, name='customer_cart'),
    path('customer/orders/', views.customer_orders_view, name='customer_orders'),
    path('customer/profile/', views.customer_profile_view, name='customer_profile'),
    path('customer/cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('customer/cart/update/<int:product_id>/', views.cart_update, name='cart_update'),
    path('customer/cart/clear/', views.cart_clear, name='cart_clear'),
    path('customer/checkout/', views.customer_checkout, name='customer_checkout'),
    path('customer/checkout/razorpay/complete/', views.customer_razorpay_complete, name='customer_razorpay_complete'),
    path('customer/checkout/razorpay/failed/', views.customer_razorpay_failed, name='customer_razorpay_failed'),
    path('customer/checkout/success/', views.customer_checkout_success, name='customer_checkout_success'),
    path('customer/order/<int:order_id>/cancel/', views.customer_cancel_order, name='customer_cancel_order'),
    path('customer/order/<int:order_id>/reorder/', views.customer_reorder, name='customer_reorder'),
    path('customer/order/<int:order_id>/rate/', views.customer_rate_order, name='customer_rate_order'),
    path('shop/start/', views.shop_start, name='shop_start'),
    path('shop/dashboard/', views.shop_dashboard, name='shop_dashboard'),
    path('shop/orders/', views.shop_orders_view, name='shop_orders'),
    path('shop/products/', views.shop_products_view, name='shop_products'),
    path('shop/settings/', views.shop_settings_view, name='shop_settings'),
    path('shop/product/<int:product_id>/delete/', views.shop_delete_product, name='shop_delete_product'),
    path('shop/order/<int:order_id>/status/', views.shop_update_order_status, name='shop_update_order_status'),
    path('shop/order/<int:order_id>/rate/', views.shop_rate_order, name='shop_rate_order'),
    path('rider/start/', views.rider_start, name='rider_start'),
    path('rider/dashboard/', views.rider_dashboard, name='rider_dashboard'),
    path('rider/deliveries/', views.rider_deliveries_view, name='rider_deliveries'),
    path('rider/completed/', views.rider_completed_orders_view, name='rider_completed_orders'),
    path('rider/earnings/', views.rider_earnings_view, name='rider_earnings'),
    path('rider/profile/', views.rider_profile_view, name='rider_profile'),
    path('rider/availability/', views.rider_toggle_availability, name='rider_toggle_availability'),
    path('rider/location/', views.rider_update_location, name='rider_update_location'),
    path('rider/order/<int:order_id>/accept/', views.rider_accept_order, name='rider_accept_order'),
    path('rider/order/<int:order_id>/status/', views.rider_update_order_status, name='rider_update_order_status'),
    path('payments/razorpay/webhook/', views.razorpay_webhook, name='razorpay_webhook'),
    path('manifest.json', views.manifest, name='manifest'),
    path('service-worker.js', views.service_worker, name='service_worker'),
]
